const express = require("express");
const cors = require("cors");
const mysql = require("mysql2/promise");
require("dotenv").config();
const path = require("path");

const app = express();
app.use(cors());
app.use(express.json()); // For parsing application/json

//Serving the static files (HTML, tailwindCSS, JavaScript.) generated by the build process of the front-end framework.
const buildPath = path.join(__dirname, "../dist");

// Serve static files from the "dist" directory
app.use(express.static(buildPath));

// Send the index.html file on the root request
app.get("/", (req, res) => {
  res.sendFile(path.join(buildPath, "index.html"), function (err) {
    if (err) {n
      res.status(500).send(err);
    }
  });
});

// Import routes

const usersRoutes = require("./routes/users");
const notificationsRoutes = require("./routes/notifications");
const resourcesRoutes = require("./routes/resources");
const tasksRoutes = require("./routes/tasks");
const financialsRoutes = require("./routes/financials");
const companiesRoutes = require("./routes/clients");
const skillsetsRoutes = require("./routes/skillsets");
const projectsRoutes = require("./routes/projects");

// Use routes
app.use("/", projectsRoutes);
app.use("/", usersRoutes);
app.use("/", notificationsRoutes);
app.use("/", resourcesRoutes);
app.use("/", tasksRoutes);
app.use("/", financialsRoutes);
app.use("/", companiesRoutes);
app.use("/", skillsetsRoutes);

// Start the server
const PORT = process.env.PORT || 8081;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
